---

- name: FLUENTD | Create fluentd group
  group:
    name: "{{ fluentd_group }}"
    state: present

- name: FLUENTD | Create fluentd user
  user:
    name: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"


- name: FLUENTD | install required libs
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ fluentd_required_libs }}"

- name: FLUENTD | install fluentd gem
  gem:
    name: fluentd
    state: present
    version: "{{ fluentd_version }}"
    user_install: no
  changed_when: false

- name: FLUENTD | install fluentd plugin gems
  gem:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ fluentd_plugins }}"
  changed_when: false